CREATE TABLE M2 (
    K1 INT,
    K2 INT,
    V VARCHAR(20),
    PRIMARY KEY (K1, K2)
);

CREATE TABLE S2 (
    K INT PRIMARY KEY,
    MFK1 INT,
    MFK2 INT,
    V VARCHAR(20),
    FOREIGN KEY (MFK1, MFK2) REFERENCES M2(K1, K2)
);