-- Dla MFK1
ALTER TABLE S2
ADD CONSTRAINT FK_S2_M2_MFK1
FOREIGN KEY (MFK1, MFK2) REFERENCES M2(K1, K2)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE S2
ADD CONSTRAINT FK_S2_M2_MFK1_SET_NULL
FOREIGN KEY (MFK1, MFK2) REFERENCES M2(K1, K2)
ON UPDATE NO ACTION 
ON DELETE SET NULL;

-- Dla MFK2
ALTER TABLE S2
ADD CONSTRAINT FK_S2_M2_MFK2
FOREIGN KEY (MFK1, MFK2) REFERENCES M2(K1, K2)
ON UPDATE SET NULL 
ON DELETE NO ACTION;

ALTER TABLE S2
ADD CONSTRAINT FK_S2_M2_MFK2_SET_NULL
FOREIGN KEY (MFK1, MFK2) REFERENCES M2(K1, K2)
ON UPDATE SET NULL 
ON DELETE SET NULL;

-- Cascade powoduje bląd przy dodaniu,
-- ale normalnie powinno usuwaz powiazane wiersze,
-- kiedy zostaje usuniety wiersz z tabeli w ktorej jest dodana
